# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 07:56
from __future__ import unicode_literals

import apps.quesresp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesRespRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether a question resposne relation is active or not')),
            ],
            bases=(apps.quesresp.models.AdminAction, models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('is_first_question', models.BooleanField(default=False, help_text='Designates if the question is the first question in the decision tree')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether a question is active or not')),
            ],
            bases=(apps.quesresp.models.AdminAction, models.Model),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether a resposne is active or not')),
            ],
            bases=(apps.quesresp.models.AdminAction, models.Model),
        ),
    ]
